### ISSUE TITLE
Browser is requesting source map, which doesn't exist on the CDN

### ISSUE THREAD

**Issue by johanbrook** [loggly/loggly-jslogger#36]
Hi there. We're loading the Loggly JS client async from your site, like this:

```js
load('//cloudfront.loggly.com/js/loggly.tracker.min.js', function() {
  // Init functions
});
```

The minified version will generate a sourcemap URL line at the bottom:

```
//# sourceMappingURL=loggly.tracker.min.map
```

which makes the browser request `http://cloudfront.loggly.com/js/loggly.tracker.min.map`, which doesn't exist. This produces an ugly 404 error in the JS console in browsers ...

***

Can you either put a source map file at http://cloudfront.loggly.com/js/loggly.tracker.min.map, or remove the source map line from the minified version of the client?

Thanks!

**Comment by growak** [comment]
+1

**Comment by janderson-beapro** [comment]
:+1:

**Comment by nporter-pa** [comment]
+1

**Comment by kittrCZ** [comment]
+ 1

**Comment by mostlyjason** [comment]
Thanks guys we'll try to get this updated in one of our upcoming deployments

**Comment by rlancer** [comment]
+1

**Comment by craigfurlong** [comment]
+1

**Comment by stefy** [comment]
+1

**Comment by mostlyjason** [comment]
This has been fixed in #40

**Comment by johanbrook** [comment]
It appears to still persist for us. See https://cloudfront.loggly.com/js/loggly.tracker.min.map : it's a 404. The JS file in question, https://cloudfront.loggly.com/js/loggly.tracker.min.js, specifies

```
//# sourceMappingURL=loggly.tracker.min.map
```

at the bottom.

**Comment by mostlyjason** [comment]
@johanbrook you should include the latest version number in your URL. We have kept this old one for legacy reasons but we encourage people to use the version numbers going forward so that people can control when they upgrade http://cloudfront.loggly.com/js/loggly.tracker-2.1.min.js

**Comment by johanbrook** [comment]
Oh, good to know. Thanks!
